name: Build Compose
# Controls when the action will run.
on:
  push:
    branches:
      - main
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout master
        uses: actions/checkout@main

      # Set up node and cache
      - name: Set Cache & Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Build the stack
        run: |
          docker-compose up -d
